#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."
ynh_backup "$install_dir/env"
ynh_backup "$install_dir/src"
ynh_backup "$install_dir/pyproject.toml"
ynh_backup "$install_dir/uv.lock"
ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_backup "/etc/systemd/system/$app.service"
ynh_backup "/etc/logrotate.d/$app"

# The data directory can be left out with --no-data (YNH_APP_BACKUP_CORE_ONLY)
ynh_backup "$data_dir" --is_big

ynh_print_info "Backup script completed for $app."
