#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Removing system configurations..."
ynh_config_remove_logrotate
ynh_config_remove_systemd
ynh_config_remove_nginx
ynh_safe_rm "/var/log/$app"

ynh_script_progression "Removal of $app completed"
