#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Stopping the service..."
ynh_systemctl --service="$app" --action="stop"

ynh_script_progression "Upgrading source files..."
setup_app

ynh_script_progression "Upgrading system configurations..."
mkdir -p "/var/log/$app"
chown "$app:$app" "/var/log/$app"
apply_config

ynh_script_progression "Starting the service..."
ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/$app.log"

ynh_script_progression "Upgrade of $app completed"
